# spring
spring:
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://${db.server}/DATABASE_NAME?${mysql.url.params}
      username: ${db.username}
      password: ${db.password}
# framework
framework:
  # swagger
  swagger:
    base-package: spring.famework.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    spring.famework: info
# mybatis plus
mybatis-plus:
  type-aliases-package: spring.famework.entity,spring.famework.model.*
  mapper-locations: classpath:mappers/*Mapper.xml
# mysql
mysql:
  url:
    params: useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
